import Head from "next/head"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import Card from "../components/Card"
import { loadPosts } from "../lib/load-posts"
import Title from "@/components/Title"

export default function Home({ posts }) {
  const fetchedPostCards = posts.map((post) => {
    return (
      <li key={post._id}>
        <Card title={post.title} author={post.author} id={post._id} />
      </li>
    )
  })

  return (
    <div className="h-screen">
      <Head>
        <title>Jaden's Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <div className="m-14">
          <Title />
        </div>
        <div className="my-12 mx-10 ">
          <ul className="flex justify-center gap-8">{fetchedPostCards}</ul>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const posts = await loadPosts()

  return {
    props: { posts },
  }
}
