import Head from "next/head"
import Card from "@/components/Card"

export default function Home({ data }) {
  const fetchedPostCards = data.map((post) => {
    return (
      <li key={post._id}>
        <Card
          title={post.title}
          author={post.author}
          id={post._id}
          published={post.isPublished}
        />
      </li>
    )
  })

  return (
    <>
      <Head>
        <title>Blog Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Blog Admin Page</h1>
        <ul className="m-8 flex flex-wrap gap-8">{fetchedPostCards}</ul>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/posts/")
  const data = await res.json()

  return { props: { data } }
}
